### PR TITLE
Change license to MIT

### PR DESCRIPTION
**Pull request by marctc**

### CODE REVIEW

**Comment by sastred** [comment]
Hi Marc,

Sorry, but the current license was proposed by @aaloy.

**Comment by marctc** [comment]
The LICENSE file points that this project is under MIT license. You probably must change the LICENSE to APSL license.

**Comment by alvaromb** [comment]
+1

Opening new issue.

The APSL license was a internal joke by @aaloy ¯_(ツ)_/¯

**Comment by marctc** [comment]
Tst tst, pasando.

**Pull request closed without merging**
